### ISSUE TITLE
Import from Excel

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#190]
When an excel file is detected, let the user choose the excel worksheet(s) to import and upload each as a file in the list.

**Comment by sgratzl** [comment]
why not importing all non-empty sheets right away? Otherwise, we need upload the file, read the worksheets via the server, let the user chooser which ones, upload it again and upload it.

**Comment by jeffbaumes** [comment]
I'd be fine with importing all non-empty sheets for now and seeing how it goes. I agree it would be much more straightforward to implement.

**Comment by jbeezley** [comment]
I don't see any big issues with doing that.  The `POST` request will just return a list of datasets.  Should be pretty straightforward to implement.
