### ISSUE TITLE
Box plots for metabolites on transform table screen

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#193]
We could add linking to the loadings plot

**Comment by jeffbaumes** [comment]
Should look something like this:

![image](https://user-images.githubusercontent.com/81305/65426481-4fa1e900-ddde-11e9-944b-62fcdc8bb7d6.png)

**Comment by jeffbaumes** [comment]
Even better may be this for better readability of metabolites. This is a before/after plot, but perhaps just an "after normalization" will be sufficient. The user can always swap between the two views by turning off normalization parameters.

![image](https://user-images.githubusercontent.com/81305/65453292-e8515c80-de10-11e9-8d67-95551cf7c870.png)

**Comment by waxlamp** [comment]
I really like the "prose" box plots. The before/after idea (not that you're necessarily suggesting we include it) could be better captured in some kind of [slope chart](https://datavizproject.com/data-type/slope-chart/).
