### ISSUE TITLE
Allow renaming of data sources

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#197]
so far the data source has the same name as the file name (including the .csv extension). Allowing the user to rename the data source and e.g. add a description would help the user when there are a lot of data sets.

**Comment by sgratzl** [comment]
@jbeezley raised the following issue:
 > I think it would be best to set the name column in the database for this to avoid overusing the schema-less metadata. If there is a desire to keep the original file name, we should create a column specifically for that.

atm the changed name is store in the existing `meta` column using the existing `/metaData` API endpoint. 

questions:
 * how should the api endpoint look like? url schema?
 * column names
 * right now the `CSVFileSchema` defines that `name` has to end with `.csv`. should we remove that validation?
 * the `ValidatedMetaboliteTable` also has a `name` column. Should this be also be updated?
 * should this be part of #235 ?

**Comment by jbeezley** [comment]
> how should the api endpoint look like? url schema?

For consistency with the other endpoints, I would go with `PUT /csv/<id>/name`.

> right now the CSVFileSchema defines that name has to end with .csv. should we remove that validation?

Yes, that validation belongs on the view anyway.  The name was never meant to be equivalent to the file name.

> the ValidatedMetaboliteTable also has a name column. Should this be also be updated?

Good point.  Yes, but I'm probably going to remove that column, so I think you can ignore it.  It isn't currently being used by the client anyway.  I added it when I thought there might be more decoupling between these two models.

> should this be part of #235 ?

The endpoints at least can be done independently.  I'm not sure where the rename feature is slated to be put in the UI.
