### ISSUE TITLE
Data source meta data

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#198]
at the current front page there are two drop downs for adding meta data to the data set. However, they are disabled and cannot be edited.

![image](https://user-images.githubusercontent.com/4129778/65041539-0278cf80-d925-11e9-870f-4e6b4472378e.png)

**Comment by jeffbaumes** [comment]
We will eventually want some basic metadata information to help people keep track of their datasets that will get saved back to the DB, e.g. measurement type (NMR, MS, etc.), sample type (serum, urine, etc.). We don't know the exact set of these and allowed values, so we just disabled them for now. I'd be ok with removing them for the time being, I doubt there is much code behind them.
