### ISSUE TITLE
Put imputation settings in the sidebar somewhere

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#200]
the clean up table uses a dialog to set the imputation settings. 

![image](https://user-images.githubusercontent.com/4129778/65042142-3f919180-d926-11e9-9ad8-5e81e41031d6.png)

the transform table (and analysis) use a left side panel to change options

![image](https://user-images.githubusercontent.com/4129778/65042161-47513600-d926-11e9-8cdb-529767227eb8.png)

So far, the imputation settings are hidden and cannot be easily explored.

**Comment by jeffbaumes** [comment]
Yes, we have had a trello card for this called "Move imputation settings to a more conspicuous spot (on the left panel somewhere)", it's good to capture it over here.

**Comment by jeffbaumes** [comment]
One solution is to have a new Imputation tab between Clean Up and Transform, and the options should appear in the second sidebar, with a view of the table with imputed values filled in.

**Comment by sgratzl** [comment]
closed in favor of #245
