### ISSUE TITLE
Transform Table Plot Sizes

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#202]
with the newly added scree plot (#182). The Transform Table looks like this on a regular Full HD screen: 

![image](https://user-images.githubusercontent.com/4129778/65042927-efb3ca00-d927-11e9-9e73-af25e0b3f4b0.png)

possible ways to deal with that:
 * allow to resize the plots in a granular way (e.g. small, medium, large). a  CSS grid layout could be used for layouting
 * allow to en/disable individual plots
 * auto adapt the plots and plot sizes to the available screen (disadvantage: unbalanced aspect ratios)

**Comment by jeffbaumes** [comment]
Yes, ideal plot size and aspect ratio is going to conflict with various browser/screen sizes. Even when you consider that we are not optimizing for mobile/tablet, there are a lot of things that can happen here. I was thinking a fixed tile size that flows is a reasonable place to start, perhaps with a maximize button added to each tile. We could go crazy with dashboarding UI here, but I'd like something relatively straightforward. Another option is a "one at a time" full screen tabbed visualizations but then the plots couldn't brush/link with each other effectively. Some tools like Excel and Simca allow visualization "windows" to float around, but a "desktop within a browser" sounds wrong to me.

Ideas welcome!

**Comment by waxlamp** [comment]
Maybe "small" and "large" buttons on each chart tile (sort of like YouTube's "theater mode") would be a happy medium, at least for now.

**Comment by jeffbaumes** [comment]
@sgratzl I'd welcome a concept PR for the following features so we and our collaborators can play with it:

* allow to resize the plots in a granular way (e.g. small, medium, large). a CSS grid layout could be used for layouting
* allow to en/disable individual plots
