### ISSUE TITLE
Breadcrumb navigation

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#206]
right now the top appbar looks like this:

![image](https://user-images.githubusercontent.com/4129778/65044575-23dcba00-d92b-11e9-9747-206c886534a3.png)

an common alternative is to have the following layout: (from left to right)
 * logo + App Title ... clickable to go back to the main screen
 * Breadcrumb ... clickable to navigate and go up in the hierarchy
 * spacer
 * Options (like Profile, General Preferences, ...) on the right side of the bar

**Comment by jeffbaumes** [comment]
I agree this would be an improvement. Not sure if we have anything for profile/preferences yet, but the other changes sound good to try. I never really liked the close button.
