### ISSUE TITLE
Data Parsing

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#208]
right now the `/csv/<id>` endpoint of a small dataset returns:

```js
{
  "columns": [
    {
      "column_header": "Name",
      "column_index": 0,
      "column_type": "key"
    },
    {
      "column_header": "m1",
      "column_index": 1,
      "column_type": "group"
    },
    {
      "column_header": "m2",
      "column_index": 2,
      "column_type": "measurement"
    },
    {
      "column_header": "m3",
      "column_index": 3,
      "column_type": "measurement"
    }
  ],
  "created": "2019-09-16T19:50:16.045404+00:00",
  "groups": "Name,m1\nA,1\nB,2\nC,3\nD,1\nE,32\nF,3\n",
  "id": "ce366700-af03-4bec-a4ed-3eda4ad28c6e",
  "imputation_mcar": "random-forest",
  "imputation_mnar": "zero",
  "measurement_metadata": "Name,m2,m3\n",
  "measurement_table": ",m2,m3\nA,5,4\nB,3,3\nC,4,3\nD,34,4\nE,3,2\nF,4,4\n",
  "meta": {},
  "name": "test-Sheet2.csv",
  "rows": [
    {
      "row_index": 0,
      "row_name": "Name",
      "row_type": "header"
    },
    {
      "row_index": 1,
      "row_name": "A",
      "row_type": "sample"
    },
    {
      "row_index": 2,
      "row_name": "B",
      "row_type": "sample"
    },
    {
      "row_index": 3,
      "row_name": "C",
      "row_type": "sample"
    },
    {
      "row_index": 4,
      "row_name": "D",
      "row_type": "sample"
    },
    {
      "row_index": 5,
      "row_name": "E",
      "row_type": "sample"
    },
    {
      "row_index": 6,
      "row_name": "F",
      "row_type": "sample"
    }
  ],
  "sample_metadata": "Name\nA\nB\nC\nD\nE\nF\n",
  "size": 64,
  "table": "Name,m1,m2,m3\nA,1,5,4\nB,2,3,3\nC,3,4,3\nD,1,34,4\nE,32,3,2\nF,3,4,4\n",
  "table_validation": []
```

which requires that the client parses the `.table, .measurement_table, .groups, .sample_metadata, .measurement_metadata` manually to get to the raw values. IMO only the server should do the parsing to avoid inconsistencies and parsing errors and deliver JSON objects (e.g. [pandas to_dict](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html)). As an alternative, the file delimiter should be normalized and also delivered to the client to avoid guessing it.

**Comment by jbeezley** [comment]
I agree this could be improved.  I considered a json serialization, but I was concerned about the serialization cost and transfer size.

> As an alternative, the file delimiter should be normalized and also delivered to the client to avoid guessing it.

What do you mean?  Isn't it always `,`?

One thing to remember about the client side parsing of the CSV files is that they are always serialized using pandas.  Even the original table (`.table`) returned with the response is read with pandas and written back out.  The `.measurement_table` is also guaranteed to have only numeric elements.  This provides a pretty reliable normalization of the CSV standard so that the client doesn't need to worry about too many edge cases.

That said, I'm open to suggestions on changing this as long as we can show that it doesn't add too much to the serialization time.

**Comment by sgratzl** [comment]
> What do you mean? Isn't it always `,`?

as you said when using `pandas.to_csv` yes it is. But there are also other similar CSV formats around, like TSV (tabular separated files) or files that are separated by semicolons `;`. The later is common especially in Germany since the comma is used there as a decimal separator (e.g. `3,5` instead of `3.5`). Most libraries (papaparse, also pandas with a proper option) can guess the used delimiter. 

re transfer size: the pure record (`rows: [{ col1: 3}, {col1: 4}]` variant is quite verbose but like column (`col1: [3, 4]`) or row wise version (`rows: [[3], [4]]`) are quite efficient. All of those variants are supported by pandas (`orient` option) thus pretty fast

**Comment by jbeezley** [comment]
> as you said when using pandas.to_csv yes it is. But there are also other similar CSV formats around, like TSV (tabular separated files) or files that are separated by semicolons ;. The later is common especially in Germany since the comma is used there as a decimal separator (e.g. 3,5 instead of 3.5). Most libraries (papaparse, also pandas with a proper option) can guess the used delimiter.

Yes, which is why it is always run through pandas before being sent to the client.  The client should never have to worry about these things.

**Comment by jbeezley** [comment]
While I don't think the CSV parsing is a particularly critical issue at this point, I do think the scope can be expanded as an exploration for a refactored API that more cleanly expresses the information needed by web client.  

Because changes to the API surface will effect the complicated interaction with the web client, we should make sure there is a clear benefit for it beyond a desire for more RESTful purity.  That said, I'm open to a more detailed proposal so we can weight the costs vs. benefits.

**Comment by sgratzl** [comment]
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_dict.html#pandas.DataFrame.to_dict

-> `orient="split"`

seems nice to work well on the client side. index access for both rows and columns and separate column and row names (similar to R data.frame)
```
{
   columns: ['A', 'B', 'C'],
   index: ['1', '2'],
   data: [
       [2,3,4],
       [5,6,7]
   ]
}
```
especially for the validated data, we could use something like that. see https://github.com/girder/viime/commit/0d7991102d093db1874cf09a30efa2e544362967. However, since we are not using the internal `to_json` of pandas, NaN have to be handled, like in https://github.com/girder/viime/blob/e5128c90ad35b03f9b176110ac07ca028329d105/viime/analyses.py#L47. On the other hand, the validated data shouldn't contain any NaN anymore.

**Comment by jbeezley** [comment]
This is for the data portion of the "large" metabolite test table:
```
> %timeit t.to_csv()                                                                                                                                    
22.4 ms ± 273 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

> %timeit json.dumps(t.to_dict(orient='split'))                                                                                                         
88.9 ms ± 208 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

> len(t.to_csv())                                                                                                                                       
249170

> len(json.dumps(t.to_dict(orient='split')))                                                                                                            
284288
```

So about 15% overhead in size and 4x the serialization time, but still way under the request latency for this file.  I think that is reasonable.

Ideally, I think we would make this change for all of the tables being passed to the client.  Do you have a sense of the work required on the client to do that?  I know the server-side changes are pretty minimal.

**Comment by sgratzl** [comment]
so far the parsing is done only at one place: 
 https://github.com/girder/viime/blob/0e1e112ece51299d16c46a104735f0adfed0f763/web/src/store/index.js#L146

**Comment by sgratzl** [comment]
we can also think of removing redundancies between `/id/validate` and `/id`. like cannot: `measurement_metadata, measurement_table, groups, sample_metadata` be derived from `table, rows. and column`?. Moreover, those derivatives aren't currently used in the client. Just, https://github.com/girder/viime/pull/260 start to use the validated data.

**Comment by jbeezley** [comment]
Yes, that is correct.  We could also just send a list of imputed values if we want to avoid sending the full metabolite table twice.

I'm :+1: on implementing this if you are looking for more to do.

**Comment by sgratzl** [comment]
closing for now
