### ISSUE TITLE
Create table cleanup interface

### ISSUE THREAD

**Issue by subdavis** [girder/viime#22]
Should probably be very similar to the one in SIMCA.

I'm going to start a 30 day trial of it to get a feel for how this interface works, and try to break that into a detailed list of mvp features.

**Comment by subdavis** [comment]
After a few minutes of playing with it, I found the data cleanup interface is actually a good bit more straightforward than I was expecting.

You can set primary and secondary keys for variables and observables.  You can flag data as qualitative, quantitative, or datetime.  The only thing I don't really get is the difference between a qualitative classification and a secondary ID classification.

There are popouts that show variables and observables, and you can toggle them on and off by clicking the rows.

I think it would be enough to just populate a select dropdown with:

* <index> (means quantitative data by default)
* primary
* secondary
* datetime
* enable/disable

Naturally the UX should go through Jared, but this is enough to get the job done until we have a better idea of what's really needed.

Screens:

![capture](https://user-images.githubusercontent.com/4214172/53585373-c0886780-3b53-11e9-89b1-b90afd95000b.PNG)
![capture2](https://user-images.githubusercontent.com/4214172/53585374-c0886780-3b53-11e9-8a4b-8eeed2000a00.PNG)
![capture3](https://user-images.githubusercontent.com/4214172/53585375-c0886780-3b53-11e9-9be5-d7ddb447e5ca.PNG)

**Comment by subdavis** [comment]
@jbeezley I see in #25 you added types for row and column.  Awesome!

```python
TABLE_COLUMN_TYPES = ['primary-id', 'secondary-id', 'numeric', 'qualitative']
TABLE_ROW_TYPES = ['header', 'sample', 'other']
```

It seems that this, the UI, and SIMCA all conflict in small ways.

1. Mutual exclusion.  You and I assume that row/col can only have 1 type, but SIMCA doesn't.  It looks like that advanced behavior is related to the "Variable Roles" which we don't care about (yet).  Our assumption seems safe for the time being.
  
2. The backed uses primary and secondary for both row and col, but you have header and sample.  I don't know what the convention should be, and this may be for someone like Tom to decide.  It's extra work to make them different -- could we make them the same for now (unless you understand the difference, of course)?

Thanks!

**Comment by jbeezley** [comment]
> Mutual exclusion...

I think I need to understand the use cases here better.  Now that I think about it, I'm not sure of the usefulness of qualitative column that *isn't* a secondary id.  I don't know how exactly a generic analysis function would operate on a table with non-numeric data...  Anyway, certainly something to save for later.

> The frontend and simca use primary and secondary for both row and col, but you have header and sample. I don't know what the convention should be, and this may be for someone like Tom to decide. It's extra work to make them different -- could we make them the same for now (unless you understand the difference, of course)?

I'm willing to change the names... I don't have the best track record for my first attempts.  I don't quite understand what you mean here.  Could you provide what you think the types should be?

**Comment by subdavis** [comment]
> I'm not sure of the usefulness of qualitative column that isn't...

Agreed.  I don't know what the difference is there.

> I don't have the best track record for my first attempts. I don't quite understand what you mean here. Could you provide what you think the types should be?

Not a critique at all -- just asking before I try to integrate :)

I have the following possible types for both row and col:

```javascript
  'data',
  'primary-key',
  'secondary-key',
```

`other` would be fine to add.  I don't have enough experience to say if they should be the same or different.   If you have a preference (or if the current types are easy to get from pandas) we can just keep those for now.

**Comment by jeffbaumes** [comment]
I like the three options for the "role" of the column/row: 'data', 'primary-key', 'secondary-key' (though I might just call this 'attribute' or something else without 'key' in it). Orthogonal to this is the "type" of the role/column, which could be 'qualitative', 'quantitative', 'temporal' (you could split 'qualitative' into 'nominal' and 'ordinal' for completeness with [Vega's type system](https://vega.github.io/vega-lite/docs/type.html)). 'data' must always be 'quantitative', but 'primary-key' and 'attribute' could be any of the types.

This is my best guess, but we should also go to Tom on this, and ask exactly the classifications he thinks should be there for rows and columns, and how they should be interpreted. Maybe @subdavis set up a 30-minute hangout with him to discuss? I'd be glad to join. Or we could invite him back to the team meeting tomorrow.

**Comment by subdavis** [comment]
@jeffbaumes I think I understand the orthogonality as you explained it, but not how it would affect our app.  Should we support keys with types other than qualitative, such as temporal?  Should our analysis care about the difference between nominal and ordinal keys?  I would definitely like to get Tom's input on this.

Unless you prefer a call, I think I can shoot Tom an email to give him some async time to consider it, and give him the option to either reply by email or join our meeting to give us his thoughts.

Thanks.

**Comment by jeffbaumes** [comment]
Thinking about it, yes a primary-key could probably always be interpreted as a string (qualitative). This leaves only 'attribute' as being any type. If we flatten role and type to disallow cases that don't make sense, the full set of tags for rows/columns might be:

* primary-key (always qualitative)
* qualitative attribute
* quantitative attribute
* temporal attribute
* data (always quantitative)

Sure, an email would help.

**Comment by subdavis** [comment]
I love the concept @jeffbaumes suggests.  This UI would have a novelty and smoothness that sets this apart from the existing tools.  It looks awesome.

* I'm concerned about rigidity and ambiguity.
* I'm also concerned about magic behavior.  If the app decides row[i] should be classified as X, the user should know about that classification and be able to change it.  MetaboAnalyst has more magic behavior than I'm comfortable with.

If rows 1,2,3 are "comment" rows (only col 0 is populated), those would get captured as metadata by this UI.  There could also be metadata the user doesn't wish to include in future analysis.

Some sort of row/column disable would solve this -- how could that fit in?

**Footnote**: I'm also not a huge fan of separating row metadata into a separate CSV as mentioned yesterday.  I'd really like for this ingest step to be able to handle nearly anything a user could throw at it gracefully.

**Comment by jeffbaumes** [comment]
I think we're done with this.
