### ISSUE TITLE
Provide users with example data

### ISSUE THREAD

**Issue by subdavis** [girder/viime#241]
I think it may be necessary in advance of the unveiling to provide users with a cache of example data from within the app. Something to make the barrier to entry very low to get users into transform/analysis as fast as possible.

Ideally we could label metadata such that users don't have to go through much cleanup to get to validation, because I think those controls still lack intuition.

In other words, I think example data would help us make a good first impression.  This will require some input from Tom and others.

**Comment by jeffbaumes** [comment]
Absolutely agree.

**Comment by waxlamp** [comment]
Including some unvalidated data might be a good idea too, to make it easy to (1) introduce production users to how it works and (2) more immediately, to make it easier for us to gather feedback from beta users on how the UI/UX is developing.

**Comment by subdavis** [comment]
Agreed.  It would be good to distinguish between "data to show off analyses" and "data to get familiar with the unique features of this tool" in the list of examples.  Perhaps grouping them separately would be necessary.

**Comment by sgratzl** [comment]
is this issue superseded by https://github.com/girder/viime/issues/369?

**Comment by jeffbaumes** [comment]
Yep
