### ISSUE TITLE
plots aren't rendered after disabling and enabling them again

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#244]
coming from https://github.com/girder/viime/pull/236

before: 
![image](https://user-images.githubusercontent.com/4129778/65339109-92bf4a80-db99-11e9-86c2-9ca9e8112ad8.png)

after clicking to hide the plot and shot it again: 

![image](https://user-images.githubusercontent.com/4129778/65339241-cd28e780-db99-11e9-8ddc-5e389f59df03.png)

**Comment by sgratzl** [comment]
the following pattern works for me

```js
export default {
  data() {
    return {
      refsMounted: false,
    };
  },
  computed: {
    reactiveUpdate() {
      if (!this.refsMounted) {
        return '';
      }
      this.update();
      return '';
    },
  },

  mounted() {
    this.refsMounted = true;
  },

  methods: {
    update() {
      if (!this.$refs.svg) {
        return;
      }
      const svg = select(this.$refs.svg);
      ...
    },
  },
};
```
```pug
svg(ref="svg", :width="width", :height="height", xmlns="http://www.w3.org/2000/svg",
    :data-update="reactiveUpdate")
  ...
```

**Comment by jeffbaumes** [comment]
@sgratzl is this fixed? I'm not seeing this in the deployed version even though #236 is merged.
