### ISSUE TITLE
Correlation network analysis

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#249]
Compute the correlation matrix between metabolites, and layout a network with edges where the absolute value of correlation is above some threshold, which should be configurable. Should look something like this:

![image](https://user-images.githubusercontent.com/81305/65426793-f1293a80-ddde-11e9-9926-272b570d3313.png)

**Comment by sgratzl** [comment]
possible layout:

![image](https://user-images.githubusercontent.com/4129778/65444069-496f3500-ddfd-11e9-9281-7fdcd1fc7539.png)

since it targets only around 1000 nodes. SVG could still be used. With the current data, I have no idea what node size could encode so I would leave it fixed for now
