### ISSUE TITLE
Generalize DataTable.vue to also render the validated table

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#250]
So, far the datatable is optimized in rendering the raw dataset. However, it could be extended to also render the validated data (or a subset of it, like just the measurements) as needed by #238

**Comment by jeffbaumes** [comment]
Could be an issue because there is no per-cell styling.

**Comment by jeffbaumes** [comment]
@sgratzl I think implementing this will unblock work on the imputation tab under Clean Up Table.

**Comment by sgratzl** [comment]
does it make sense to try to generalize it? The new DataTable is pretty simple and the logic is mostly to correctly do the types

**Comment by jeffbaumes** [comment]
As long as a reasonable attempt is made to avoid lots of repeated code/styling, it doesn't matter to me. We could generalize DataTable.vue, or pull out things like utility functions/styles and make a separate ImputedTable, or maybe even do something else.
