### ISSUE TITLE
Architecture design for data integration

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#252]
Architecture should include:

* How to deal with multiple algorithms on the server and UI
* How to deal with algorithm parameters on the server and UI
* How to select the datasets to integrate, do they need to be datasets that pass validation?
* Keeping record of provenance (source datasets). What happens if source dataset pretreatment options change?
* Where the action to integrate datasets lives in the UI
* Where the new integrated dataset lives in the UI
* How to model PCA-based columns in the database

**Comment by sgratzl** [comment]
can we close this issue?

**Comment by jeffbaumes** [comment]
Yes
