### ISSUE TITLE
create logo for viime

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#257]

**Comment by jtomeck** [comment]
[viime.zip](https://github.com/girder/viime/files/3677035/viime.zip) (with svg)
![viime](https://user-images.githubusercontent.com/1560779/65974859-af7e3c80-e43b-11e9-9a87-1a0f18f9e335.png)

**Comment by waxlamp** [comment]
This looks pretty cool!

I feel like it *could* possibly be hard to read if you don't already know what it says. I wonder what it would look like if the Is received [tittles](https://en.wikipedia.org/wiki/Tittle) (keeping the same height and color they do now).

**Comment by jeffbaumes** [comment]
I feel it could look worse with i-dots, I like the simplicity here. I also would rather @jtomeck be working on the front page rather than fiddling with the logo 😄.  If he has time after that we can come back and refine the logo.

**Comment by jeffbaumes** [comment]
To be clear: suggestions are welcome on this PR. My qualification was more of a directive for Jared for what to do first.

**Comment by subdavis** [comment]
I think it's perfect.  I also wonder if serifs or tittles or dots could make it look too much like the vimeo logo.  But hey, everybody's a critic.

https://press.vimeo.com/brand-guidelines

**Comment by mgrauer** [comment]
@jtomeck A bit jauntier please

**Comment by waxlamp** [comment]
@mgrauer you have to precise about these things.

20% jauntier, please.

**Comment by jtomeck** [comment]
Hey guys, I'm building a shed to keep my bike in. Any suggestions on what color it should be?

Joking aside I appreciate the feedback. I think we're okay when it comes to looking different enough from the vimeo logo as theirs is more "cursive-y" and playful. The VIIME logo I created is Open Sans Black Italic with some rounding modifications from me.

**Comment by mgrauer** [comment]
To be clear, my earlier comment was a joke. I think this logo looks great.

**Comment by waxlamp** [comment]
To call this done, I think we just need to add an appropriately sized image of the logo to replace `logo.png` in the assets directory in the project, and maybe make a single-letter "V" version to use as the favicon.

**Comment by jeffbaumes** [comment]
I agree. I had thought the three green things would be the favicon, but probably the v is better.

There might be a larger logo on the front page and a smaller one tucked into the toolbar, so I'm ok waiting on figuring that and the favicon out until the @jtomeck does the front page.

**Comment by waxlamp** [comment]
> I agree. I had thought the three green things would be the favicon, but probably the v is better.
> 

I think the "Vii" being the favicon is a good idea; it would be more distinctive than, say, a Vue V or a Vimeo V or a Vicarious Visions V.

> There might be a larger logo on the front page and a smaller one tucked into the toolbar, so I'm ok waiting on figuring that and the favicon out until the @jtomeck does the front page.

I'll open some issues and link them to the front page one. Is this one considered done, then?

**Comment by jeffbaumes** [comment]
Yep
