### ISSUE TITLE
Investigate boxplot dot size

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#287]
Document what it means (perhaps in ? icon in plot header).

If it's too confusing or nonstandard, we could also just make all the dots the same size.

**Comment by sgratzl** [comment]
seems like that d3-boxplots implements the following logic:
https://github.com/akngs/d3-boxplot/blob/28c0b43ff1af2c70ba60df1b0196bd8606c02777/src/boxplot.js#L210

if differentiates between a regular outlier and a `farout` outlier. 
a `farout` outlier is an outlier that is outside the double wisker length (`q1 - 2 * 1.5 * iqr`)

**Comment by jeffbaumes** [comment]
I don't see an option for making the farout outliers the same size, so it will probably be best to go in the documentation for the plot. I'll close this and open a task to have a help/description button that describes the plot and plot options.
