### ISSUE TITLE
Add help icon to plots

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#288]
Clicking the icon would open a help dialog describing the plot and plot options.

Would this be another named slot in VisTile? I could see the documentation for some plots or analyses being quite lengthy, could include embedded images, etc. so we probably want a slot that accepts a full component, as opposed to assuming the help will be a text-only string.

Placeholder help would be fine with this PR, then we can fill in the help later.

**Comment by sgratzl** [comment]
Are you aiming for an in-place help or a link to an external page like a wiki

**Comment by waxlamp** [comment]
I think this could be added to the currently existing slot on VisTile.

To answer @sgratzl's question, I envision a hybrid approach: a modal dialog that pops up and describes what the plot is, and then a link to, e.g., Wikipedia for a more comprehensive "learn more" link.

**Comment by jeffbaumes** [comment]
Let's go with in-place help for now, which as @waxlamp says could link out to other places.
