### ISSUE TITLE
Analysis column selection race condition.

### ISSUE THREAD

**Issue by subdavis** [girder/viime#302]
If you click through a couple of columns quickly, some selections turn on and off after you've clicked them.

I Imagine the fix would be to only change the selected status of the columns involved in a call to `SET_DATASET_SELECTED_COLUMNS` rather than resetting them all from the server.

Dataset load would still set all columns from server.

It's possible we need to do more elaborate version control here though, maybe with timestamps or something.   Depends on whether we consider multi-session concurrent access a feature or a happy accident.

**Comment by sgratzl** [comment]
in the current version the store will be updated before the server is ready thus avoiding the race condition and better UX

https://github.com/girder/viime/blob/1c2c32cbf9f5b7d541ac3ba962fafc64f5b4952e/web/src/store/index.js#L572-L580
