### ISSUE TITLE
Misc Heatmap bugs.

### ISSUE THREAD

**Issue by subdavis** [girder/viime#303]
First of all, sorry for approving #266  when I hadn't run it locally.

* The mouseover animation is a bit too heavy and causes the UI to lock up when you mouse around on the view with the debug console open.  I know this isn't a normal operating condition, but if something is slow enough to break when debug is open, it probably won't run well on cheap hardware.  Should probably dig deeper into the heft of the render loop and test with much larger file. A set of test files as mentioned in #281 would also help here.  Might also have to sacrifice some of the nice highlighting for speed.
* It looks like you're redrawing the highlighting after every mouse move.  Could we debounce it by not firing the redraw if the highlighted cell hasn't changed from the last mousemove event?
* the resize animation is quite slow.  If you drag the page around, it takes the tree a while to catch up.  Is it possible to drop the animation and just render it immediately?
* the animation for adding and removing rows and columns is also pretty slow: the heatmap redraws immediately and then the tree struggles to catch up.  
* resizing the page causes the heatmap to disappear.  It seems to come back on mouseover.
* there's some odd behavior with the selection cursor when width < height.  Screenshot below.
* I think the plus and minus buttons may be backward.  `+` hides things and `-` adds them back.

![Screenshot from 2019-10-02 16-13-32](https://user-images.githubusercontent.com/4214172/66078256-ab334b80-e52f-11e9-8119-a510689994f3.png)

Also included a flame graph for mouseover redrawing.

![Screenshot from 2019-10-02 16-03-26](https://user-images.githubusercontent.com/4214172/66078671-6f4cb600-e530-11e9-8a2a-b63fc2922c8d.png)

Would it make sense to revert #266 until these issues are fixex?  Again, sorry for not trying this out before I approved it.  

cc @sgratzl

**Comment by jeffbaumes** [comment]
I don't feel like a revert is needed. @sgratzl can address these issues in a new PR.
