### ISSUE TITLE
Fix padding/margin on correlation graph

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#305]
There is unwanted padding/margin at the top:

![image](https://user-images.githubusercontent.com/81305/66127680-44a73f80-e5ba-11e9-98a8-8d20b2ed4750.png)

**Comment by sgratzl** [comment]
added intentionally by @subdavis with https://github.com/girder/viime/commit/a20777a18f13f33062b646df71162498dcb7be8e

**Comment by jeffbaumes** [comment]
@subdavis is there a fix where we can we have the controls line up while having the vis be full-screen?

**Comment by subdavis** [comment]
I'm not able to reproduce this....

![Screenshot from 2019-10-03 11-15-50](https://user-images.githubusercontent.com/4214172/66139931-40395180-e5cf-11e9-9395-150c14a29cd5.png)

What dataset and settings did you use to get this result?  If you did it on viime.org, you can share the URL here directly, but you'll still need to tell me the correlation settings.  thanks.

**Comment by jeffbaumes** [comment]
If you make your browser window a bit smaller vertically you could probably see the cutoff on the top left node. It's easy to replicate on the zoomable view PR (#300).
