### ISSUE TITLE
Data integration

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#337]
Some initial guidelines discussed by @jbeezley @sgratzl @jeffbaumes:

* There would be a button on the upload page to create a new integrated dataset.
* A dialog lets the user choose two datasets, an integration method, and a new dataset name.
* The new dataset would appear in the file list and would have extra metadata fields linking to the source datasets.
* The integrated table would be based on a snapshot of the source tables at the time and would NOT be recomputed if the source tables change.
* The new data would have a metadata row containing the source table that contributed to that column.

**Comment by sgratzl** [comment]
>     * A dialog lets the user choose two datasets, an integration method, and a new dataset name.

do we have to limit to two?

**Comment by jeffbaumes** [comment]
> do we have to limit to two?

I don't believe we have any algorithms that will work with more than two. I'll send out an email to collaborators to clarify.
