### ISSUE TITLE
Download error

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#363]
Refused to load the image 'blob:https://viime.org/a712bd55-3df6-4557-80c1-7e7b24cdd3bb' because it violates the following Content Security Policy directive: "default-src * data: 'unsafe-eval' 'unsafe-inline'". Note that 'img-src' was not explicitly set, so 'default-src' is used as a fallback.

**Comment by sgratzl** [comment]
as far as I understood we need to add: 
```
Content-Security-Policy: blob:
```
to the `Content-Security-Policy` header
