### ISSUE TITLE
Have a way to use sample data from data page

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#369]
One way to do this is to make a set of csv model ids that are public and are loaded into the system on deploy if not yet present.

These models may also need to be in groups of two or more. The general solution may be to have every "sample data" selection to come as a group, where some groups only have one element.

**Comment by sgratzl** [comment]
ui wise: where should this be and how should it look wise

db wise: how to identify template datasets. We can add a database flag for that but how to set it UI wise? If we add a general flag everyone can create those sample datasets

**Comment by jeffbaumes** [comment]
Here's a crude mockup of a UI that could work (note the page is now called Manage Data instead of Upload Data):

![image](https://user-images.githubusercontent.com/81305/67518207-4a042100-f672-11e9-9ca8-95a678fc29cf.png)

The select button would bring up a dialog with a list of named dataset groups to choose from which would then be populated in the data list.

As for the DB, I am not sure what will be best. Seems datasets would need a "sample" flag as well as a grouping identifier. Does not seem right that arbitrary users would be able to mark a dataset as a sample dataset from the UI. Ideally someone like Tom could upload a set of data, configure it in the right way, then a file (or set of files) could be made into a sample dataset "somehow". Maybe it's by sharing the CSV identifier(s) with devs to add to the repo/db? Would also seem that the sample data should be saved to the repo so it's not lost if the app needs to be redeployed from scratch. Open to other thoughts here, it's not straightforward.

**Comment by sgratzl** [comment]
from a database point of view a dataset consists of
 * a file stored on the server containing the original CSV file
 * a DB entry in the `CSVFile` table
 * N DB entries in tables such as `GroupLevel`, `TableColumn`, `TableRow`
 * a DB entry in the `ValidatedMetabolite` table (for transformation settings)

So, we can create a python script (similar to the `viime-create-tables` ones) that imports sample datasets. But still remains: how to identify them, how to simple create/manipulate them. 

As an alternative we can also implement an import/export features that dumps the above information in a JSON for one more datasets and also implement a way to import them. 

In both cases another problem is how to handle migrations like adding new attributes
