### ISSUE TITLE
Color columns by dataset type

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#375]
From Tom's email. We have a row with the dataset for each column, and it would be good to be able to color by this in all analysis views, but particularly the heatmap.

Instead of making the dataset number a special case, this could be enabled in general for metadata rows. I could see it being more intuitive for the file name or some other identifier ("serum") to show up in a legend instead of the 1, 2, etc. number.

@sgratzl Any thoughts on how to solve this generally?

**Comment by sgratzl** [comment]
see also #323 otherwise we don't know whether it is a number (like age) or a categorical value (like gender)

**Comment by jeffbaumes** [comment]
This issue now seems to be higher priority, while selection coloring is less of a priority (Tom requested selection coloring to be removed). The options seem to be (1) color by generic metadata row (with potentially row type autodetection) that defaults to the dataset row if it is a merged dataset, or (2) a checkbox explicitly for coloring by dataset with some hard coded logic. I am ok with either one of these approaches, ideally we would choose the one which will make the code less messy and easier to update later on.
