### ISSUE TITLE
PCA tab

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#380]

**Comment by waxlamp** [comment]
Is the goal here to have a special tab just for PCA (and labelled as such,
etc.)?

**Comment by jeffbaumes** [comment]
Yep. The PCA plots would remain in the Transform Table page as well, but there would also be a page under Analysis just for PCA.

**Comment by jeffbaumes** [comment]
Specifications from the meeting just now:
* Show Loading, Score, and Scree plots
* Place plot options in the sidebar instead of in per-plot options
