### ISSUE TITLE
Color negative correlations differently from positive ones in network view

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#385]

**Comment by waxlamp** [comment]
I'd suggest a diverging colormap, going through a neutral color like white or very light gray (retaining a solid stroke to indicate the nodes, rather than relying on the fill color for this purpose).

**Comment by sgratzl** [comment]
so far the correlation value is encoded in the link strength. should we double encode it using a color scale or just use binary colors (positive/negative)?

**Comment by waxlamp** [comment]
I was imagining it displayed on the nodes, which of course doesn't make
sense. You're right, stick with binary colors and let the magnitude be
encoded in the strength (or possibly a second time in the link width).
