### ISSUE TITLE
ANOVA sum of squares is 0 error

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#401]
I get this on the server on a specific merged datasource. It may have been due to low-variance columns. Regardless, it made the client produce unrecoverable errors because of a missing `data` prop that should be guarded against.

```
ERROR in opencpu: b'residual sum of squares is 0 (within rounding error)\n\nIn call:\nAnova.lm(mod, type = "III")\n'
```

**Comment by jeffbaumes** [comment]
I believe this is indeed happening when there is a low-variance column that has not been masked. I believe we should catch the server error, send it to the client, and report an error where the ANOVA table would normally appear with something such as: "ANOVA cannot be performed. Mask low variance columns and try again."

**Comment by sgratzl** [comment]
please try again

**Comment by mvandenburgh** [comment]
This issue is resolved by https://github.com/girder/viime/pull/605
