### ISSUE TITLE
For the footer, let's follow data.kitware.com and put a Privacy Notice link to https://www.kitware.com/privacy

### ISSUE THREAD

**Issue by subdavis** [girder/viime#424]
For the footer, let's follow data.kitware.com and put a Privacy Notice link to https://www.kitware.com/privacy

_Originally posted by @jeffbaumes in https://github.com/girder/viime/pull/253#issuecomment-551857715_

CC @jtomeck

**Comment by jeffbaumes** [comment]
Fixed in #435
