### ISSUE TITLE
Don't hard-code element size for plots

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#43]
We need to get rid of [hard-coded sizes](https://github.com/girder/metabulo/blob/c71b6ffdb8168e05ccceb79abc4bcd6949db4dd8/web/src/components/views/Transform.vue#L125) for vis components.

attn: @subdavis

**Comment by sgratzl** [comment]
see also #256

**Comment by subdavis** [comment]
What should be the strategy for automatic sizing?

I think it would be sufficient to have 

* a row-wrap situation
* handle page resize and user click resize events from a mixin, remove the width prop on `<Name>VisTile.vue`
* calculate width from within that mixin, pass it to the individual tiles.

**Comment by waxlamp** [comment]
The current wrapping situation that came with the sizing buttons seems like it could continue to work, right?

**Comment by sgratzl** [comment]
is this discussion still valid?

**Comment by subdavis** [comment]
I don't think so.  I think you can close it.

#274 fixed this right?
