### ISSUE TITLE
Add feedback link (Google form)

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#433]
For now, a quick fix is to add this Google form link (target="_blank") instead of the inline form:

https://forms.gle/WjJccPExa7JnNKHq9

Right now my email will get notified of new responses which I can share with the team. We'll set up a better feedback method in the future.

**Comment by sgratzl** [comment]
can you share the form itself with me, please

**Comment by sgratzl** [comment]
We might also wanna add an "Association" field to get where the people are working (which lab, company, ...)

**Comment by jeffbaumes** [comment]
I just followed our generic kitware.com contact form. Normally the email will indicate association, but I was also considering adding that. Maybe "Organization" is a good field name.
