### ISSUE TITLE
loadings plot scale

### ISSUE THREAD

**Issue by sgratzl** [girder/viime#472]
so far the loading plot scales are fixed to -1 ... 1 regardless of the data based on the assumption that correlations values are just between -1 and 1. However, with only small values in the data, the plot is a dot in the center. 

possible axis scales:
 1. each axis to min/max of the actual values
 1. each axis to `-Math.max(abs(min), abs(max))` to `Math.max(abs(min), abs(max))` .. symmetric
 1. both axes to min/max of either of those
 1. both axis to symmetric of either of them

**Comment by sgratzl** [comment]
@jeffbaumes what do you prefer?

**Comment by sgratzl** [comment]
current: 

![image](https://user-images.githubusercontent.com/4129778/68802275-9f0cd480-062b-11ea-9c97-ffe86d7002c2.png)

> * each axis to min/max of the actual values

![image](https://user-images.githubusercontent.com/4129778/68802224-869cba00-062b-11ea-99f3-6092d95292be.png)

> 
> * each axis to `-Math.max(abs(min), abs(max))` to `Math.max(abs(min), abs(max))` .. symmetric

![image](https://user-images.githubusercontent.com/4129778/68802189-77b60780-062b-11ea-8c9e-565022de0a01.png)

> 
> * both axes to min/max of either of those

![image](https://user-images.githubusercontent.com/4129778/68802355-c663a180-062b-11ea-91fd-8476212ed5a9.png)


> 
> * both axis to symmetric of either of them

![image](https://user-images.githubusercontent.com/4129778/68802323-b8158580-062b-11ea-9d7e-34e33374e156.png)

**Comment by waxlamp** [comment]
I think it's important to keep (0,0) at the center of the plot, so a symmetric approach is best. Ultimately, allowing a zoom and pan interaction, with a reset button, is probably the correct solution here.
