### ISSUE TITLE
Add google analytics key to netlify environment

### ISSUE THREAD

**Issue by jbeezley** [girder/viime#532]
See https://github.com/girder/viime/blob/5e8b02e6b888de2d41b9684a46b82d55abe97912/web/src/main.js#L34

This variable should be set to `UA-6042509-40` when building.

**Comment by waxlamp** [comment]
@AlmightyYakob accomplished this with a `netlify.toml` file in the root of the Multinet client project, just FYI.

**Comment by mvandenburgh** [comment]
Is there any preference for using the netlify UI vs a `netlify.toml` file in the repo (like @waxlamp mentioned) to define environment variables? So far I have been using the UI but that might not be immediately apparent to someone who isn't familiar with netlify.

**Comment by jbeezley** [comment]
I don't have a preference.  The UI would be appropriate for secret values, but both the sentry dsn and google gtag are served the client anyway.

**Comment by waxlamp** [comment]
The good thing about a `netlify.toml` file is that it's somewhat more apparent to people what variables are needed by the deployment. The alternative is to write up documentation somewhere about what is needed.
