### ISSUE TITLE
VUE_APP_SERVER_ADDRESS - not documented and no default

### ISSUE THREAD

**Issue by jeffbaumes** [girder/viime#588]
I keep getting bit by this one, and need to remember to do the following in my shell where I run `yarn serve` (usually after getting obscure console errors):

```
export VUE_APP_SERVER_ADDRESS=http://localhost:5000
```

Could this have a default? At the very least this step should be documented in the README.

**Comment by waxlamp** [comment]
Better yet, this should be set in the `.env_*` files with a default, and the docs should explain what it is and if/when to change it.

**Comment by jeffbaumes** [comment]
This is something that needs to be set in the terminal where `yarn serve` runs, so the `.env` may not be available unless you do something like `pipenv run yarn serve`.

**Comment by jbeezley** [comment]
Vue cli automatically sets variables from `.env` files.  See https://cli.vuejs.org/guide/mode-and-env.html

**Comment by waxlamp** [comment]
Thanks for that info, @jbeezley. I had mistakenly thought that Yarn itself includes .env support.

**Comment by jeffbaumes** [comment]
So, sounds like the answer might be to create a file `web/.env_example` containing

```
export VUE_APP_SERVER_ADDRESS=http://localhost:5000
```

Plus there would be instructions in the README directing people to copy it to `web/.env` (which is `.gitignore`'d) before `yarn serve`? This would follow the pattern of the top-level `.env` for the server.

**Comment by mvandenburgh** [comment]
There is a default value for it:
https://github.com/girder/viime/blob/622fc7671de13dc0a206841726e2fe126d749e22/web/src/main.ts#L25

When running in development mode `VUE_APP_SERVER_ADDRESS` is defined as a relative URL `/api/v1'/`, which is then proxied to `http://localhost:5000` by the dev server defined in `vue.config.js`. 

I can document this, assuming no one has started doing it?

**Comment by jeffbaumes** [comment]
I think I was getting hit by this other use of the env variable which did not have a fallback. This line is removed in the more recent versions of your ROC PR.

https://github.com/girder/viime/pull/587/commits/51ba51fcd5e4f90dc380491a3d39118afa044d10#diff-50134e41893a56d201fddecabc1d07bbR45

So I think we can assume things will work as expected in dev environments without setting an env variable and this issue can be closed.
