### ISSUE TITLE
Heatmap labels, ANOVA no results, network view zoom

### ISSUE THREAD

**Issue by joannawolthuis** [girder/viime#597]
Hi crew! I've been taking a look at your tool, thanks for all your work on it! I noticed that the heatmap does show compound names,  but they are tiny(illegible) if you have many. Would you consider making the compound names (and sample names) visible on mouse hover in a tooltip?
Furthermore it seems I have no ANOVA results - I would add something like 'no significant hits found' as now I just have an empty screen and do not know if that is due to an error or due to no hits being found. 
Lastly (if you prefer i make seperate issues for this, please let me know!) the network view is cool and would be even cooler if you could zoom to specific sections for dense networks, or if this automatically happens if you click a link. :)

Kind regards,
Joanna

**Comment by waxlamp** [comment]
Hi @joannawolthuis! :wave:

Thanks for the feedback. I can split your comments into separate issues, though if you do it you can remain the "opener" for those issues. Then it will be easier for our team to address them. Please let me know how you'd like to proceed.

**Comment by joannawolthuis** [comment]
Hi @waxlamp ! That's OK with me :D Go ahead!

**Comment by waxlamp** [comment]
Closing in favor of #598, #599, and #600.
