### ISSUE TITLE
a few issues using the tool

### ISSUE THREAD

**Issue by jkanche** [girder/viime#607]
Hi All,

Great work on the tool. It looks pretty neat and responsive! I used the Cancer chemo muscle (NMR) dataset, tested it on firefox, let me know if I should run this on a different browser -

- MNAR and MCAR imputation needs a None selection. It defaults to always using MCAR selection.
- Zooming in/out resixes the window but doesn't resize the plots itself
- It would be nice If I could zoom on an area of the plot especially for PCA loadings plot to check and see what metabolites cluster together. 
- the PCA Scree plot description says the vertical cutoff lines are provided at 50, 80 and 90, but I only see 2 lines. also good to annotate these (If I'm saving the plots). 
- Metabolite Box plot, when I group by treatment, the plot disappears 
- Wilcox and ANOVO Volcano plots don't seem to render. 
- In correlation networks, whats the different between an orange edge vs a grey edge ? I understand the thickness is stronger correlation but not the color difference. 

seems like I might have put too many things in a single issue. Let me know if i should break this down! 

Thanks,
Jay

**Comment by waxlamp** [comment]
Thanks for the issue report, @jkanche!

It will definitely help to split these up into separate issues. You can do it yourself, or I can do it--let me know what you prefer :cat:

**Comment by jkanche** [comment]
I would leave that to you, thank you!

**Comment by waxlamp** [comment]
Closing in favor of #615, #616, #617, #618, #619, #620, and #621.
