### ISSUE TITLE
Clarify setup instructions

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#611]
The JOSS reviewers (@joannawolthuis and @jkanche) have both requested improved setup instructions (see https://github.com/openjournals/joss-reviews/issues/2410#issuecomment-668530730 and https://github.com/openjournals/joss-reviews/issues/2410#issuecomment-668917059).

@joannawolthuis, @jkanche: would you mind providing some detail of where things went wrong for you in following the setup procedure in the [README](https://github.com/girder/viime#viime)?

**Comment by waxlamp** [comment]
Hi @joannawolthuis and @jkanche! This [new section of the README](https://github.com/girder/viime#getting-started-docker-compose), explains how to spin up the server backend locally using Docker. Please check it out and let us know if it works for you.

**Comment by jkanche** [comment]
cool, thanks for updating the instructions. Is there a reason why the web client cannot be a docker container and has to be run separately ?

**Comment by waxlamp** [comment]
> cool, thanks for updating the instructions. Is there a reason why the web client cannot be a docker container and has to be run separately ?

I don't think there's anything preventing it, but since the web client build is a standard NPM workflow, we didn't feel a need to do it.

If you run `yarn install` followed by `yarn serve` from the `web/` directory, things should go pretty smoothly. Are you running into any trouble with that process?

**Comment by jkanche** [comment]
No I was able to run everything locally. I thought since everything is already setup using docker, It might make it easier to include the client as part of the docker rather than have to do an extra step. but this works as wel

**Comment by waxlamp** [comment]
Ah, I see. That idea does make sense and I've opened #637 to track it.

I will go ahead and close this issue since things seem to be working better than before. If you run into new problems, feel free to re-open.
