### ISSUE TITLE
MNAR and MCAR imputation needs a None selection. It defaults to always using MCAR selection.

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#615]
via @jkanche

**Comment by jkanche** [comment]
What I had trouble (may be its a UI thing) is what if i only want to choose either MCAR or MNAR on all imputations but not a combination of these methods ?

**Comment by waxlamp** [comment]
Thanks for explaining!

We are actually following a general algorithm for imputation from [Armitage et al.](https://onlinelibrary.wiley.com/doi/abs/10.1002/elps.201500352). Under this approach, MCAR and MNAR are designations of different types of missingness, with each type being fixable using one of several choices. For Viime, this means you don't get a choice of using MNAR or MCAR; it's something that's performed for you heuristically.

We have added some text to the paper to clarify how this works.

Let me know if you have other questions or concerns about this.
