### ISSUE TITLE
Metabolite Box plot, when I group by treatment, the plot disappears

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#619]
via @jkanche

**Comment by jkanche** [comment]
may be this url helps - (https://viime.org/#/app/pretreatment/de83db69-3537-4f65-bb9f-279f1a6893eb/analyze/boxplot)

![image](https://user-images.githubusercontent.com/399324/90986360-4cfcc600-e550-11ea-8967-8bef9ca2ecab.png)

**Comment by waxlamp** [comment]
Thank you, this is helpful! We will look into what's going on.

**Comment by waxlamp** [comment]
It seems like there may be a race condition in the underlying processing routines that sometimes gets triggered when selecting the group column in the Clean Up Table view. To fix it, you can unset the group column (by making it into metadata, for example), then reload the page, then set that column back to Group. You should see the values grouped into distinct colors, and then the grouping by treatment in the box plot will work again.
