### ISSUE TITLE
Automated testing

### ISSUE THREAD

**Issue by joannawolthuis** [girder/viime#623]
Hi! I see your testing folders, but is this process automated or do you run manually?

Cheers,
Joanna

**Comment by waxlamp** [comment]
Good morning @joannawolthuis!

If you check out the [CircleCI spec](https://github.com/girder/viime/blob/master/.circleci/config.yml) you can see how we run our testing suite in CI.

**Comment by waxlamp** [comment]
Closing; please re-open if you have further concerns or questions.
