### ISSUE TITLE
Comparison to other tools

### ISSUE THREAD

**Issue by joannawolthuis** [girder/viime#624]
Hi there! In the context of the JOSS review, a comparison with other tools is required. I couldn't find one in the manuscript, so if there isn't a supplemental that I missed, I'd like to request such a comparison (perhaps with one of those cliche comparison tables :) )

**Comment by waxlamp** [comment]
Thanks for pointing this out. We will get right on it :cat:

**Comment by waxlamp** [comment]
@joannawolthuis, we just added some commits to the paper text with some discussion of comparison to our closest "competitor". Please take a look and let me know what you think!

**Comment by joannawolthuis** [comment]
Hi @waxlamp, thanks for adding this section! I have one comment - please double check the facts on MetaboAnalyst, they do have more missing value imputation options than the 1/5 lowest value one, KNN means., replace with mean/median, PPCA etc (although no MCAR etc. estimation):
![image](https://user-images.githubusercontent.com/16805477/92458321-8165b880-f1c5-11ea-8a68-d70dde31dc34.png)

Secondly, maybe you could consider adding at least another 2 tools or so that are similar, I know there are other tools that compare themselves to MetaboAnalyst as well (WebSpecmine is one example that is R-based, and there are more, MzMine), perhaps with a comparison table? With that it'd be a better overview I think :)
