### ISSUE TITLE
Add description for PCA/PLSDA/Group Prediction Analyses

### ISSUE THREAD

**Issue by mvandenburgh** [girder/viime#627]
There's currently no descriptions for these three analyses in the "Analyze Data" page (see below)

![analyze_page](https://user-images.githubusercontent.com/37340715/90177561-bb839c00-dd78-11ea-8821-19ad99ec984a.png)

(PLSDA is not merged yet as of the time I'm submitting this issue)

**Comment by waxlamp** [comment]
@jeffbaumes, this seems to be done. I'm going to close this but please re-open if anything is missing.
