### ISSUE TITLE
Use optional chaining inside Vue templates once upgraded to Vue 3

### ISSUE THREAD

**Issue by mvandenburgh** [girder/viime#633]
When VIIME is upgraded to Vue 3 we can use optional chaining to clean up some of the JS inside templates. (like here https://github.com/girder/viime/blob/master/web/src/components/vis/AnovaVolcanoPlotTile.vue#L139 for example).

[Vue 2 doesn't support optional chaining inside templates](https://github.com/vuejs/vue/issues/11088).

**Comment by jeffbaumes** [comment]
We'll be sure to keep this in mind when we get to Vue 3.
