### ISSUE TITLE
Implement VIP score script and display bar chart

### ISSUE THREAD

**Issue by mvandenburgh** [girder/viime#635]
Implement the VIP score R script from Lilian into the server and display the data as a bar chart. 

I did some preliminary work for the server side and pushed the code for that here #636. One thing worth mentioning about that PR is that the response time of the PLS-DA endpoint is now ~5-6 seconds because the Flask server now needs to make **three** requests to the opencpu server when the endpoint is called (one for scores, one for loadings, and now one for VIP scores). This is due to limitations from returning the data from the opencpu server as an R `dataframe` (see [here](https://github.com/girder/viime/pull/613#discussion_r472311839) for more details). It may be worth investigating if a less structured data type than a `dataframe` could be used to return all three of these results in one opencpu request.

The client will need to display a bar graph on the PLS-DA analysis page next to the loadings and score plots. See the VIP scores R script for an example of what that should look like.

**Comment by jeffbaumes** [comment]
For now, we just want to finish this up and implement the bar chart, and possibly deal with a less structured data type later on.
