### ISSUE TITLE
Do a style review for PCA vis

### ISSUE THREAD

**Issue by waxlamp** [girder/viime#65]
attn @jtomeck @subdavis 

I'd like to have a general style review for the PCA vis component, that addresses things like the following:
- colors/opacities for chart components such as axes, etc.
- do we need gridlines on the chart itself?
- what should the tooltip element look like?
- colors used for the data and ellipses
- data point size
- data point interaction style (e.g., should the points have an interaction "halo" to make them easier to target with the mouse?)

**Comment by jeffbaumes** [comment]
I think this is done. @waxlamp reopen if needed.
