### ISSUE TITLE
Score plot scatter colors not matching confidence ellipse

### ISSUE THREAD

**Issue by dchiquit** [girder/viime#672]
When any page with a score plot is loaded, the color of the points in the scatter plot will not match the color of the associated confidence ellipse. Resizing the window will fix this.
I can reliably reproduce this by refreshing the PCA, PLSDA, or OPLSDA plots on my local deployment. I can't reproduce it on viime.org.

**Comment by waxlamp** [comment]
What branch does this happen on?

**Comment by dchiquit** [comment]
I've found a way to reproduce it 100% on viime.org.
1. Load the first two sample datasets, `Cancer chemo muscle (NMR)` and `Cancer chemo liver (NMR)`.
2. View the first dataset, then go to `Analyze Table` > `PCA`. Confidence ellipse color should match the dots.
3. Without navigating anywhere else, directly open the PCA analysis for the second dataset (`Cancer chemo liver (NMR)` > `Analyze Table` > `PCA`).
4. The confidence ellipses should now be mismatched with the data points.

This is different from the initially reported behavior. If you open either of those datasets and open the PCA page, there is a small probability that the point colors will be rendered incorrectly the first time (there will be a yellow set of points, which I haven't seen happen normally). I've also seen this happen on viime.org, although it seems more reliable locally. I assume that sorting out the coloring code will fix both.
