### ISSUE TITLE
Downloading PNG not working for BoxPlots and Group Prediction (AUC)

### ISSUE THREAD

**Issue by biswapriyamisra** [girder/viime#703]
Hello,

the PNG image download for Box Plots (single or multiple?) does not work.
Same is also true for Group Prediction (AUC) downloads.

Jobs: 
https://viime.org/#/app/pretreatment/3bd5b9cd-fc6a-46ca-9798-62b08c5dda02/analyze/boxplot
https://viime.org/#/app/pretreatment/3bd5b9cd-fc6a-46ca-9798-62b08c5dda02/analyze/roc

Thanks,
Biswa

![box_plots](https://user-images.githubusercontent.com/27797664/105622636-14338680-5e39-11eb-9838-7caf76fec847.JPG)
![roc_auc](https://user-images.githubusercontent.com/27797664/105622637-1564b380-5e39-11eb-80aa-a4a6ab1d17c2.JPG)

**Comment by jeffbaumes** [comment]
Thanks for the bug report. I also seem to not be able to download PNG right now and I'm not seeing a console error. We'll look into it.

**Comment by jeffbaumes** [comment]
This should be fixed on viime.org. Let us know if you see further issues.

**Comment by jbeezley** [comment]
I think the deploy failed.  See https://app.circleci.com/pipelines/github/girder/viime/2130/workflows/12c90c8f-2080-4258-82f2-045cd3484b12/jobs/5697.

It looks like pip dropping python 2.  We'll need to update the tox file to use python3.  It may require updating the circleci workflow, but I'm not sure.

**Comment by jeffbaumes** [comment]
Download PNG worked for me where it didn't before, so could it have deployed? That's a bit of a mystery if it didn't in fact deploy.

**Comment by jbeezley** [comment]
That is strange.  Looking at circleci, the last successful deploy was 2 months ago.

**Comment by jeffbaumes** [comment]
I see @dchiquit 's one-line change (`el` line) in the Chrome dev tools when on viime.org 🤷‍♂️ 

![image](https://user-images.githubusercontent.com/81305/106182703-36950f00-616d-11eb-8fe9-9166c53efb6b.png)

**Comment by jbeezley** [comment]
Oh, I see.  That's for client side changes which is done by netlify.  The server part of #705 didn't get deployed, but that's a fix for a different issue.
